export const FETCH_QUIZES_START = 'FETCH_QUIZES_START';
export const FETCH_QUIZES_SUCCESS = 'FETCH_QUIZES_SUCCESS';
export const FETCH_QUIZES_END = 'FETCH_QUIZES_END';
export const FETCH_QUIZ_BY_ID_SUCCESS = 'FETCH_QUIZ_BY_ID_SUCCESS';

export const QUIZ_SET_STATE = 'QUIZ_SET_STATE';
export const FINISH_QUIZ = 'FINISH_QUIZ';
export const NEXT_QUESTION = 'NEXT_QUESTION';
export const RETRY_QUIZ = 'RETRY_QUIZ';

export const ADD_QUESTION = 'ADD_QUESTION';
export const RESET_QUIZ = 'RESET_QUIZ';

export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
